[package]
name = "aleo-std-cpu"
version = "1.0.3"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Convenience method for retrieving CPU information"
license = "Apache-2.0"
edition = "2021"
