[package]
name = "aleo-std-timer"
version = "1.0.1"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A timer to conveniently time code blocks"
license = "GPL-3.0"
edition = "2021"

[dependencies.colored]
version = "2"
optional = true

[features]
default = []
timer = [ "colored" ]
